- cmd/go-tpc/main.go
- cmd/go-tpc/misc.go
- pkg/workload/workload.go
- tpcc/check.go
Add checkCondition6 and checkCondition11.
I found that checkCondition11 always failed after running tpcc run command for a while . PTAL @zhouqiang-cl 
> tpcc: add checkCondition6 and checkCondition11

- tpch/dbgen/driver.go
- tpch/dbgen/order_line.go
- tpch/dbgen/part_psupp.go
- tpch/ddl.go
- tpch/query.go
- tpch/workload.go
Because of `CONSTRAINT FOREIGN KEY` of some tables, rows of the `orders` table need to be inserted before all related lineItems, so they weren't enable to be inserted by batch.
To speed up data loading, I modified some DDLs and removed these foreign key constraints.
PTAL @zhouqiang-cl
> tpch: speed up data loading

- tpcc/check.go
- tpcc/ddl.go
The constant is not propagated correctly for some check SQLs, the check for a single warehouse would scan all the warehouses in the table.
So we pass it manually to get away with this issue.
The check time goes down from 96s to 20s for 10 warehouses, the improvement would be large if we have more warehouses.
Also removed some indices because they are not used.
> make check faster and remove unnecessary index

- README.md
- cmd/go-tpc/main.go
- cmd/go-tpc/misc.go
- cmd/go-tpc/tpcc.go
- go.mod
- go.sum
- pkg/load/batch_loader.go
- pkg/util/file.go
- pkg/workload/base.go
- pkg/workload/workload.go
- tpcc/ddl.go
- tpcc/load.go
- tpcc/workload.go
- tpch/loader.go
- tpch/workload.go
Fix https://github.com/pingcap/go-tpc/issues/14
This PR also supports specifying tables now. If `--csv.table` is not set, by default it will generates all 9 tables data.
Example usage:
```
./go-tpc tpcc prepare --csv.output data --csv.table orders --csv.table customer --csv.table history  --warehouses 100
```
> Support csv file in data preparing

- README.md
- cmd/go-tpc/tpcc.go
- tpcc/workload.go
Please merge #21 first
The previous `csv.table` flag needs to be specified repeatedly, which is not that user-friendly.
This PR updates that flag, rename it to `csv.tables`, table names separated by `,`. It can be used like:
```
./bin/go-tpc tpcc --warehouses 4 prepare --csv.output data --csv.tables history,orders,customer
```
> Improve table specify flag

- tpcc/new_order.go
- tpcc/payment.go
In this [pr](https://github.com/pingcap/go-tpc/pull/15), I updated the history table. But didn't update the insert statement against table history, which will be executed in `tpcc run`. This pr fixes this bug.
> Update tpcc run statement against table history

- README.md
- cmd/go-tpc/main.go
- cmd/go-tpc/misc.go
- cmd/go-tpc/tpcc.go
Signed-off-by: mahjonp junpeng.man@gmail.com
For nowadays, go-tpc tpcc only supports generate csv format file, so we can simplify the cmd flags. In the future, when we support more output format(e.g. Rocksdb sst file), we need add another flag `-t` to specify it.
> tpcc: Simplify cmd flags

- pkg/load/batch_loader.go
The csv writer should check error instead of returning nil.
> Return error in csv flush

- cmd/go-tpc/main.go
- cmd/go-tpc/misc.go
- pkg/measurement/hist.go
- pkg/measurement/measure.go
Signed-off-by: Liu Cong <innerr@gmail.com>
1, The TPM was not correct, especially happened on error TPM, it caused by the incorrect `start-time` of `hist` , this PR fixed that
2, This PR added a param `--summary`:
- When it's true, print summary measurements on each tick
- When it's false(by default), print current measurements on each tick, and print summary's on each 10 ticks
3, Print `conflicted` errors
> Fixed: error TPM. Added: show current TPM

- cmd/go-tpc/main.go
- cmd/go-tpc/tpcc.go
Set it lower may improve performance.
> add flag for setting runtime.GOMAXPROCS

- README.md
- cmd/go-tpc/misc.go
- cmd/go-tpc/tpcc.go
- pkg/workload/workload.go
- tpcc/check.go
- tpcc/csv.go
- tpcc/ddl.go
- tpcc/delivery.go
- tpcc/load.go
- tpcc/new_order.go
- tpcc/order_status.go
- tpcc/payment.go
- tpcc/prepare.go
- tpcc/stock_level.go
- tpcc/workload.go
- tpch/workload.go
Fixes #24
User facing changes
1. Add a new flag `output-type`
2. Rename `output` to `output-dir`
> Refactor csv generator

- README.md
- docs/import-to-tidb.md
- docs/tidb-lightning.toml
fixes #37
Please merge this after #36 is merged
> Add doc about lightning usage

- cmd/go-tpc/main.go
- cmd/go-tpc/tpch.go
- tpch/workload.go
This pr sets the default value of sf to 1 and fix a bug which cause tpch workload hangs when close db conn.
> TPCH: set default sf to 1

- cmd/go-tpc/tpch.go
- tpch/dbgen/driver.go
- tpch/ddl.go
- tpch/workload.go
Signed-off-by: JaySon-Huang <jayson.hjs@gmail.com>
A an option "--tiflash" support creating tiflash replica when loading tpc-h dataset.
> Add option to create tiflash replica in TPC-H

- README.md
- cmd/go-tpc/tpch.go
- tpch/ddl.go
- tpch/workload.go
Signed-off-by: JaySon-Huang <tshent@qq.com>
In `tpch prepare`, add some options to support automatically analyze tables after data loaded.
> Add options to analyze tables after tpc-h data loaded

- README.md
- cmd/go-tpc/tpcc.go
- pkg/measurement/hist.go
- tpcc/workload.go
Add Keying Time and Thinking Time between txn execution and two flags.
``` bash
Usage:
go-tpc tpcc run [flags]
Flags:
-h, --help   help for run
--wait   including keying & thinking time described on TPC-C Standard Specification
```
For example.
```
./bin/go-tpc tpcc --warehouses 4 run --wait
```
> tpcc: add wait times on each transactions

- cmd/go-tpc/main.go
- cmd/go-tpc/misc.go
- pkg/measurement/hist.go
- pkg/measurement/hist_test.go
- pkg/measurement/measure.go
- pkg/workload/workload.go
- tpcc/csv.go
- tpcc/workload.go
- tpch/workload.go
Currently, TPC-C and TPCH share the same style `Summary` output but provide custom output are preferred because, on TPC-H, we only care about the average duration of each SQLs, total duration, and other metrics we don't care.
So, to TPC-C, I change the summary output follow the style:
```
[Summary] DELIVERY - Takes(s): 152.1, Count: 43, TPM: 17.0, Sum(ms): 1553, Avg(ms): 36, 90th(ms): 40, 99th(ms): 48, 99.9th(ms): 48
[Summary] DELIVERY_ERR - Takes(s): 152.1, Count: 1, TPM: 0.4, Sum(ms): 32, Avg(ms): 32, 90th(ms): 32, 99th(ms): 32, 99.9th(ms): 32
...
[Summary] KEYINGTIME-DELIVERY - 2.0s
[Summary] KEYINGTIME-NEW_ORDER - 18.0s
[Summary] KEYINGTIME-ORDER_STATUS - 2.0s
[Summary] KEYINGTIME-PAYMENT - 3.0s
[Summary] KEYINGTIME-STOCK_LEVEL - 2.0s …
```
> Workload: customize statistics output for different workload

- tpcc/check.go
- tpch/workload.go
Here is a tiup bench TPCH panic log:
```log
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4f8832]
goroutine 39 [running]:
database/sql.(*Rows).close(0x0, 0x0, 0x0, 0x0, 0x0)
/usr/local/go/src/database/sql/sql.go:3063 +0x72
database/sql.(*Rows).Close(0x0, 0x30, 0x8beb00)
/usr/local/go/src/database/sql/sql.go:3059 +0x33
github.com/pingcap/go-tpc/tpch.Workloader.Run(0xc0001b6000, 0xe64d80, 0x9c28c0, 0xc00026e090, 0x3, 0x9b8cc0, 0xc0000b3320)
/go/pkg/mod/github.com/pingcap/go-tpc@v1.0.4-0.20200511044254-883c1a10d555/tpch/workload.go:154 +0x4d7
main.execute(0x9c28c0, 0xc00026e090, 0x9c71e0, 0xc000152050, 0x8fb1ae, 0x3, 0x3, 0x0, 0x0) …
```
> TPCH: fix a panic issue

- Dockerfile
- Makefile
This PR add a Dockerfile and support build and push docker image of go-tpc via `make docker-build` and `make docker-push`
Signed-off-by: Aylei <rayingecho@gmail.com>
> Add make docker-* targets

- tpcc/workload.go
current code use `keyingTime` value as think time seems be wrong
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/go-tpc/64)
> tpcc: use right think time value

- cmd/go-tpc/misc.go
- cmd/go-tpc/tpcc.go
- tpcc/workload.go
Reasons: tpcc prepare check sometimes aren't necessary.
Changes: 1.add new flag(no-check) in cmd. 2.add new field(NoCheck) in tpccConfig 3.check tpccConfig.NoCheck in misc.go: checkPrepare
Signed-off-by: Cadmus <CadmusJiang@gmail.com>
> feature: add new flag(no-check), help skip check when tpcc prepare

- Makefile
- ch/workload.go
- cmd/go-tpc/main.go
- cmd/go-tpc/misc.go
- cmd/go-tpc/tpcc.go
- cmd/go-tpc/versioninfo.go
- pkg/load/batch_loader.go
- pkg/util/versioninfo.go
- tpcc/load.go
- tpcc/new_order.go
- tpcc/workload.go
- tpch/loader.go
- tpch/workload.go
The go-tpc often panics with an error when the connection is closed because of some kinds of transient faults, it's too annoying particularly when preparing a big dataset into the databases。
This PR adding two flags providing a retry commit mechanism when a batch insert fails, this mechanism tries to re-commit failed statements according to how we set it on flags.
close #71
> *: add a flag to retry commit when data loading fails on prepare stage

- pkg/workload/base.go
- tpcc/workload.go
This PR fixes the invalid connection error when the tidb-server is killed
```
[mysql] 2021/03/27 07:50:25 packets.go:36: unexpected EOF
[2021-03-27 07:50:25] execute run failed, err invalid connection
[2021-03-27 07:50:25] execute run failed, err invalid connection
[2021-03-27 07:50:25] execute run failed, err invalid connection
execute run failed, err invalid connection
execute run failed, err invalid connection
execute run failed, err invalid connection
[2021-03-27 07:50:25] execute run failed, err invalid connection
execute run failed, err invalid connection
[mysql] 2021/03/27 07:50:25 packets.go:36: unexpected EOF
[mysql] 2021/03/27 07:50:25 packets.go:36: unexpected EOF
```
> tpcc: refresh conn if pingContext fails

- cmd/go-tpc/tpcc.go
- pkg/load/batch_loader.go
- tpcc/load.go
- tpcc/workload.go
This PR ignores the non-first `Duplicated entry` error.
```log
load to district in warehouse 672
exec statement error: invalid connection, may try again later...
[mysql] 2021/04/01 07:31:43 packets.go:36: unexpected EOF
...
exec statement error: Error 1062: Duplicate entry '672-1' for key 'PRIMARY', may try again later...
exec statement error: Error 1062: Duplicate entry '780-1' for key 'PRIMARY', may try again later...
load to district in warehouse 1088
load to warehouse in warehouse 1188
load to stock in warehouse 1188
exec statement error: Error 1062: Duplicate entry '672-1' for key 'PRIMARY', may try again later...
exec statement error: Error 1062: Duplicate entry '780-1' for key 'PRIMARY', may try again later...
load to district in …
```
> tpcc: ignore the non-first `Duplicated entry` error

- cmd/go-tpc/tpcc.go
- tpcc/csv.go
- tpcc/ddl.go
- tpcc/ddl_test.go
- tpcc/workload.go
The tpcc test is a good match for partitioned tables, since the tables have a natural composite primary key including 'warehouse id'. This makes it good to test the different int based partitioning schemes like HASH, LIST and RANGE partitioned tables.
Currently only HASH was supported, this adds RANGE as well as two distributions of LIST partitioning (LIST partitioning, like it HASH or RANGE)
> tpcc: Add list and range partitioned table options

- README.md
Users may wonder whether the go-tpc support prepares data with multiple threads and how to do it. I think we'd better add the 'threads' flag on the readme so that users could directly know it's ok for go-tpc.
> Update readme: add the `-T` flag on the `prepare` and `run` guide

- README.md
- cmd/go-tpc/main.go
- cmd/go-tpc/rawsql.go
- rawsql/workload.go
enables go-tpc to run custom sql queries.
usage: `./bin/go-tpc rawsql run --query-files $path-to-query-files`
> rawsql: introduce rawsql command

- cmd/go-tpc/main.go
Fix the issue #104 : fail to create a db which did not exist.
> Initialize unknown db (#104)

- cmd/go-tpc/ch_benchmark.go
It hasn't been possible to change the transactional workload when running `go-tpc ch run`.
This PR fixes that by adding a weight flag to `go-tpc ch run` in the same manner as the tpcc benchmark.
> Added tpcc weights for ch-benchmark

- .gitignore
- ch/workload.go
- cmd/go-tpc/main.go
- cmd/go-tpc/misc.go
- cmd/go-tpc/tpch.go
- pkg/workload/workload.go
- rawsql/workload.go
- tpcc/csv.go
- tpcc/workload.go
- tpch/check.go
- tpch/ddl.go
- tpch/workload.go
[Plan replayer](https://docs.pingcap.com/tidb/dev/sql-plan-replayer#use-plan-replayer-to-save-and-restore-the-on-site-information-of-a-cluster) is to help us reproduce the environment which is used by optimizer to decide how to generate Plan for each query. This is quite useful for us to debug if the plan unexpected changed.
This requests supports dump plan replatyer for tpch test.
The dumped zip file saved the following file:
/*
|-q1_time.zip (plan replayer results for q1)
|-q2_time.zip
|-q3_time.zip
|-...
*/ 
As we need status port to download plan replayer results from tidb-server, a quick example is like fowllowing:
```sh
go-tpc tpch --sf=1 run -H <host> -P 4000 -S 10080 --use-plan-replayer true
```
> support plan replayer for tpch

- ch/ddl.go
- ch/workload.go
- cmd/go-tpc/ch_benchmark.go
- cmd/go-tpc/rawsql.go
- cmd/go-tpc/tpch.go
- pkg/plan-replayer/replayer.go
- rawsql/workload.go
- tpch/workload.go
Signed-off-by: yisaer <disxiaofei@163.com>
support plan replayer for ch like following:
```sh
go-tpc ch --warehouses <warehouses> -T <count> -t <count> --time <time> -H <host> -P <dbPort> -D <database> -S <statusPort> --use-plan-replayer true run
```
support plan replayer for rawsql like following:
```sh
go-tpc  rawsql run --query-files q1.sql --time <time> -H <host> -P <dbPort> -D <database> -S <statusPort> --use-plan-replayer true
```
> support plan replayer for ch,rawsql

- tpcc/workload.go
> tpcc: calculate tpmTotal and show it in summary

- cmd/go-tpc/ch_benchmark.go
- cmd/go-tpc/main.go
- cmd/go-tpc/rawsql.go
- cmd/go-tpc/tpch.go
Allow specifying a list of hosts & ports to connect to (just like sysbench), eg. `--host 172.16.4.1,172.16.4.2 --port 4000,4001` means connecting to 172.16.4.1:4000, 172.16.4.1:4001, 172.16.4.2:4000, 172.16.4.2:4001 round-robin.
> *: support for connecting to multple instances directly

- tpch/query.go
- tpch/workload.go
Fix q15 failure in collecting plan-replayer mode by forbidding running multi sql in `execute`
> Fix tpch q15 failure in collecting plan-replayer mode

- ch/workload.go
- cmd/go-tpc/ch_benchmark.go
- cmd/go-tpc/rawsql.go
- cmd/go-tpc/tpch.go
- pkg/util/output.go
- rawsql/workload.go
- tpch/workload.go
1. Support --use-explain for CHbenchmark.
2. Always drain the result by calling `rows.Next()` and then report the duration. Otherwise the reported CHbenchmark query time may be inaccurate sometimes.
3. Use logger to output stderr to avoid interleaving results.
> Add explain support for CHbenchmark

- ch/workload.go
I was surprised by wrong QpH results in ch benchmark. It seems, test reports it wrong - we need 3600/(sum/count) , and sum is in ms, so have to multiply by 1000.
> Report is misleading in ch benchmark

- cmd/go-tpc/ch_benchmark.go
- cmd/go-tpc/main.go
- cmd/go-tpc/tpcc.go
- cmd/go-tpc/tpch.go
- go.mod
- go.sum
In containerized deployments, Go runtime, by default, uses the total number of CPU cores available on the machine as the value of GOMAXPROCS, without considering the CPU quota of the container. This can lead to suboptimal performance and potential throttling issues as more goroutines may get scheduled than the available CPU quota.
Uber's automaxprocs library automatically adjusts the GOMAXPROCS value to match the Linux container's CPU quota, leading to more efficient CPU usage and potentially better performance.
> *: set right GOMAXPROCS

- cmd/go-tpc/main.go
- go.mod
- go.sum
- Using tls=preferred, the server accepts a TLS connection from the client but is also okay if the client does not switch to encryption.
- upgrade go-sql-driver > 1.7.0 to use this feature for older version MySQL server https://github.com/go-sql-driver/mysql/pull/1370.
> Support connect to both tls and non-tls server

- cmd/go-tpc/tpch.go
- tpch/workload.go
Set some session variables known to be effective for tpch before each tpch query to tune performance. And also add flags to turn it on/off and override the default variables.
```
--enable-query-tuning         Enable query tuning by setting specified session variables (default true)
```
`tidb_default_string_match_selectivity=0.1`: For optimal join order, esp. q9.
`tidb_opt_join_reorder_threshold=60`: For general optimal join order.
`tidb_prefer_broadcast_join_by_exchange_data_size=ON`: For better join type between broadcast join and partition join.
> tpch: add query tuning configs for tpch

- cmd/go-tpc/main.go
Close: #185 
Add tls config for connecting mysql with tls enabled
Manually test:
```
[ec2-user@ip-10-0-19-25 cert]$ ./go-tpc -H 10.0.153.232 -U u1 -P 4000 tpcc --warehouses 1 prepare
2024/11/23 21:42:36 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined
failed to ping db, err Error 1045 (28000): Access denied for user 'u1'@'10.0.19.25' (using password: NO)
panic: failed to connect to database when loading data
goroutine 1 [running]:
github.com/pingcap/go-tpc/tpcc.NewWorkloader(0x59c338?, 0xc0003e9540?)
/Users/Projects/db-will/go-tpc/tpcc/workload.go:110 +0x8bd
main.executeTpcc({0xb4c776, 0x7})
/Users/Projects/db-will/go-tpc/cmd/go-tpc/tpcc.go:66 +0x205
main.registerTpcc.func1(0xc000144900?, {0xb49b4c?, 0x4?, 0xb49b50?})
/Users/Projects/db-will/go-tpc/cmd/go-tpc/tpcc.go:96 +0x1f …
```
> Add tls support for mysql client

- cmd/go-tpc/tpch.go
- pkg/util/version.go
- pkg/util/version_test.go
Issue Number: #187 
According to [System Variables | TiDB Docs](https://docs.pingcap.com/tidb/stable/system-variables#variable-reference), set TiDB QueryTuningVars only when connected to TiDB(>=7.1.0). 
It's still a rough comparison to quickly fix the compatibility issue.
> fix: set tidb tunning variables only when connected to valid tidb

- ch/workload.go
- cmd/go-tpc/misc.go
This PR fixes a critical issue where CH benchmark queries would continue executing indefinitely even after the specified timeout period expired.
> fixes: Queries continuing after timeout in CH benchmark

- ch/workload.go
- cmd/go-tpc/misc.go
CH benchmark requires the revenue1 view for analytical queries. During normal prepare flow, this view is created in prepareView() method.
However, when using CSV data ingestion, the prepare stage is skipped and the view won't exist. So we create it here when action is "run" to ensure the view is available regardless of how data was loaded.
> feat(ch): ensure revenue1 view creation for CSV data ingestion
