pingcap/go-tpc

- tpcc/check.go
Attach each checks with it's consistency condition name
> tpc-c: attach each checks with it's consistency condition name

- cmd/go-tpc/main.go
- cmd/go-tpc/tpch.go
- tpch/query.go
- tpch/workload.go
> tpch: add run part

- tpcc/new_order.go
- tpcc/payment.go
- tpcc/workload.go
Use prepared statements for new order and payment. 
We can support order status, stock level, and delivery later. 
I have run for a while and then use `check` to pass the consistency check.
> add stmts for new order and payment

- cmd/go-tpc/main.go
- pkg/measurement/hist.go
- tpcc/delivery.go
- tpcc/new_order.go
- tpcc/order_status.go
- tpcc/payment.go
- tpcc/stock_level.go
- tpcc/workload.go
Now The performance is similar to benchmarksql.
> support batch new order and delivery

- pkg/measurement/hist.go
- tpcc/new_order.go
- tpcc/workload.go
Make all statements prepared and change the output from QPS to TPM like 
```
NEW_ORDER - Takes(s): 79.9, Count: 13044, TPM: 9791.1, Sum(ms): 468862, Avg(ms): 35, 95th(ms): 64, 99th(ms): 80, 99.9th(ms): 112
ORDER_STATUS - Takes(s): 80.0, Count: 1146, TPM: 859.9, Sum(ms): 9510, Avg(ms): 8, 95th(ms): 16, 99th(ms): 20, 99.9th(ms): 24
PAYMENT - Takes(s): 79.9, Count: 12456, TPM: 9352.0, Sum(ms): 185182, Avg(ms): 14, 95th(ms): 32, 99th(ms): 48, 99.9th(ms): 80
STOCK_LEVEL - Takes(s): 79.9, Count: 1184, TPM: 888.6, Sum(ms): 23930, Avg(ms): 20, 95th(ms): 32, 99th(ms): 32, 99.9th(ms): 40
DELIVERY - Takes(s): 89.9, Count: 1297, TPM: 865.9, Sum(ms): 109559, Avg(ms): 84, 95th(ms): 128, 99th(ms): 192, 99.9th(ms): 256
```
> more prepared statements

- tpcc/ddl.go
It will be used in checkCondition10 to speed up check.
> add h_c_w_id index in history table

- README.md
Add the content about how to override `host`, `port` and `db` flags on readme.
> Readme: add usage part

- .github/workflows/workflow.yaml
> fix action workflow

- .github/workflows/release.yaml
- .goreleaser.yml
> Add release gh action

- pkg/load/batch_loader.go
This PR fixes the previous way we use csv writer. The previous buf field seems redundant because csv writer itself has a buffer.
> Fix csv batch flush

- README.md
> Update table creation readme

- ch/ddl.go
- ch/workload.go
- cmd/go-tpc/misc.go
> Fix set tiflash replica

- ch/ddl.go
- ch/workload.go
- cmd/go-tpc/misc.go
> Measure ch error

- tpcc/stock_level.go
In case statistics is not up to date.
> add hint for stock level statement

- cmd/go-tpc/main.go
- cmd/go-tpc/tpch.go
fix https://github.com/pingcap/tiup/issues/886
> fix `client has multi-statement capability disabled` error

- .goreleaser.yml
- Makefile
- cmd/go-tpc/versioninfo.go
- install.sh
- pkg/util/versioninfo.go
- add a flag to retry commit when data loading fails on prepare stage (#72)
- add the version command #73
> release v1.0.5

- cmd/go-tpc/tpch.go
- tpch/dbgen/cust.go
- tpch/dbgen/driver_test.go
- tpch/dbgen/lineitem.go
- tpch/dbgen/nation.go
- tpch/dbgen/order.go
- tpch/dbgen/part.go
- tpch/dbgen/part_supp.go
- tpch/dbgen/region.go
- tpch/dbgen/supp.go
- tpch/workload.go
> support tpch csv export

- .github/workflows/release.yaml
- .github/workflows/workflow.yaml
- .gitignore
- Dockerfile
- go.mod
enjoy the performance improvement from the go1.18.
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>
> *: upgrade go1.18

- ch/workload.go
- cmd/go-tpc/ch_benchmark.go
- cmd/go-tpc/main.go
- cmd/go-tpc/rawsql.go
- cmd/go-tpc/tpcc.go
- cmd/go-tpc/tpch.go
- go.mod
- go.sum
- pkg/measurement/hist.go
- pkg/measurement/hist_test.go
- pkg/measurement/measure.go
- pkg/util/output.go
- rawsql/workload.go
- tpcc/workload.go
- tpch/workload.go
Hi all, I'm working on this PR to give a try for outputting the result as table style. Originally, the output is a line and not aligned. With table style output, we can get better user experience and it can be much more convenient to copy values.
The output would like this:
in comparison, the original output is like this:
This is a simple try and I have not written it in a better way. I would first like to get some feedback on this approach and later I can make it better.
Any feedback is welcomed.
> use table output for better user experience

- cmd/go-tpc/ch_benchmark.go
Add the following three options to `ch run`, which overwrite `conn-params`, `host`, `port` when opening db for analytical processing.
```
--ap-conn-params string   Connection parameters for analytical processing
--ap-host string          Database host for analytical processing
--ap-port int             Database port for analytical processing
```
> ch: support connecting to a specified instance for ap

- .goreleaser.yml
> also release arm64 binaries

- pkg/workload/base.go
- tpch/workload.go
> tpch: check connection before each run iteration

- README.md
- ch/workload.go
- cmd/go-tpc/ch_benchmark.go
- cmd/go-tpc/tpch.go
- tpch/ddl.go
- tpch/workload.go
Signed-off-by: Lloyd-Pottiger <yan1579196623@gmail.com>
support add multiple tiflash replica
> support add multiple tiflash replica

- cmd/go-tpc/ch_benchmark.go
> ch: fix index-out-of-range error when ch prepare

- .github/workflows/release.yaml
> ci: release latest build

- .github/workflows/release.yaml
> ci: fix latest release build

- .github/workflows/release.yaml
> ci: fix a typo in package step

- install.sh
> bump to v1.0.9

- ch/query.go
> fix(ch): fix bug in ch query q2
